"""Add authentication fields to users

Revision ID: 69c7d5638cf8
Revises: 
Create Date: 2026-05-04 19:01:18.745820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69c7d5638cf8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username for login'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='User interests, topics, sources, and content preferences'),
    sa.Column('schedule_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Schedule configuration for automated podcast generation'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('podcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('script', sa.Text(), nullable=True, comment='Generated podcast script content'),
    sa.Column('audio_url', sa.String(length=1024), nullable=True, comment='URL or path to generated audio file'),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='podcaststatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if generation failed'),
    sa.Column('podcast_metadata', sa.Text(), nullable=True, comment='Additional metadata in JSON format'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcasts_created_at'), 'podcasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_podcasts_id'), 'podcasts', ['id'], unique=False)
    op.create_index(op.f('ix_podcasts_status'), 'podcasts', ['status'], unique=False)
    op.create_index('ix_podcasts_status_created', 'podcasts', ['status', 'created_at'], unique=False)
    op.create_index('ix_podcasts_user_created', 'podcasts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_podcasts_user_id'), 'podcasts', ['user_id'], unique=False)
    op.create_index('ix_podcasts_user_status', 'podcasts', ['user_id', 'status'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('podcast_id', sa.UUID(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False, comment='Number of tokens consumed by GPT-4o'),
    sa.Column('elevenlabs_characters', sa.Integer(), nullable=False, comment='Number of characters processed by ElevenLabs TTS'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='Total end-to-end latency in milliseconds'),
    sa.Column('cost_estimate', sa.Float(), nullable=False, comment='Estimated cost in USD for this podcast generation'),
    sa.Column('news_fetch_ms', sa.Integer(), nullable=True, comment='Time taken to fetch news articles in milliseconds'),
    sa.Column('script_generation_ms', sa.Integer(), nullable=True, comment='Time taken to generate script in milliseconds'),
    sa.Column('audio_generation_ms', sa.Integer(), nullable=True, comment='Time taken to generate audio in milliseconds'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cost_estimate >= 0', name='check_cost_non_negative'),
    sa.CheckConstraint('elevenlabs_characters >= 0', name='check_characters_non_negative'),
    sa.CheckConstraint('latency_ms >= 0', name='check_latency_non_negative'),
    sa.CheckConstraint('tokens_used >= 0', name='check_tokens_non_negative'),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_cost_estimate', 'metrics', ['cost_estimate'], unique=False)
    op.create_index(op.f('ix_metrics_created_at'), 'metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_metrics_id'), 'metrics', ['id'], unique=False)
    op.create_index(op.f('ix_metrics_podcast_id'), 'metrics', ['podcast_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_podcast_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_created_at'), table_name='metrics')
    op.drop_index('ix_metrics_cost_estimate', table_name='metrics')
    op.drop_table('metrics')
    op.drop_index('ix_podcasts_user_status', table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_user_id'), table_name='podcasts')
    op.drop_index('ix_podcasts_user_created', table_name='podcasts')
    op.drop_index('ix_podcasts_status_created', table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_status'), table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_id'), table_name='podcasts')
    op.drop_index(op.f('ix_podcasts_created_at'), table_name='podcasts')
    op.drop_table('podcasts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
