"""add_firecrawl_cost_tracking_to_metrics

Revision ID: e8cb09eb222c
Revises: 69c7d5638cf8
Create Date: 2026-05-06 13:01:57.106601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cb09eb222c'
down_revision = '69c7d5638cf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('firecrawl_searches', sa.Integer(), nullable=False, server_default='0', comment='Number of Firecrawl search API calls'))
    op.add_column('metrics', sa.Column('firecrawl_scrapes', sa.Integer(), nullable=False, server_default='0', comment='Number of Firecrawl scrape API calls'))
    op.add_column('metrics', sa.Column('firecrawl_cost', sa.Float(), nullable=False, server_default='0.0', comment='Estimated Firecrawl API cost in USD'))
    # Add check constraints for non-negative values
    op.create_check_constraint('check_firecrawl_searches_non_negative', 'metrics', 'firecrawl_searches >= 0')
    op.create_check_constraint('check_firecrawl_scrapes_non_negative', 'metrics', 'firecrawl_scrapes >= 0')
    op.create_check_constraint('check_firecrawl_cost_non_negative', 'metrics', 'firecrawl_cost >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraints first
    op.drop_constraint('check_firecrawl_cost_non_negative', 'metrics', type_='check')
    op.drop_constraint('check_firecrawl_scrapes_non_negative', 'metrics', type_='check')
    op.drop_constraint('check_firecrawl_searches_non_negative', 'metrics', type_='check')
    # Drop columns
    op.drop_column('metrics', 'firecrawl_cost')
    op.drop_column('metrics', 'firecrawl_scrapes')
    op.drop_column('metrics', 'firecrawl_searches')
    # ### end Alembic commands ###
